version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.13

  pre_build:
    commands:
      - apt-get update && apt-get install -y zip
      - wget https://releases.hashicorp.com/terraform/0.12.18/terraform_0.12.18_linux_amd64.zip
      - unzip terraform_0.12.18_linux_amd64.zip
      - mv terraform /usr/local/bin/ 
      - terraform --version

  build:
    commands:
      - cd test
      - go test -timeout 60m -v
